// <auto-generated />
using MachineLearningMachine3000.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineLearningMachine3000.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240306112641_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineLearningMachine3000.Data.FactCase", b =>
                {
                    b.Property<int>("DateId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceIdId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID_ID");

                    b.Property<int>("SummeVonEingangAktiv")
                        .HasColumnType("int")
                        .HasColumnName("Summe_von_Eingang_Aktiv");

                    b.Property<int>("SummeVonEingangNeu")
                        .HasColumnType("int")
                        .HasColumnName("Summe_von_Eingang_Neu");

                    b.ToTable("Fact_Cases", "DP_FC_156");
                });

            modelBuilder.Entity("MachineLearningMachine3000.Data.FactCaseForecast", b =>
                {
                    b.Property<int>("DateId")
                        .HasColumnType("int");

                    b.Property<int>("SummeVonEingangNeuForecast")
                        .HasColumnType("int")
                        .HasColumnName("Summe_von_Eingang_Neu_Forecast");

                    b.ToTable("Fact_Cases_Forecast", "DP_FC_156");
                });
#pragma warning restore 612, 618
        }
    }
}
